### ISSUE TITLE
Disable gradient in titles?

### ISSUE THREAD

**Issue by Owyn** [tpenguinltg/winclassic#11]
a checkbox to do that would be nice
cuz there's no gradient in my windows titles so I couldn't really preview how it'd look cuz gradient was covering it all over

**Comment by tpenguinltg** [comment]
@Owyn You should see it on the site now. When you uncheck the "Titlebar gradients" checkbox, the change isn't automatic: you'll have to change the titlebar colour first. I admit it's not ideal, but hopefully that'll do for now.
